# Generated by Django 2.2.5 on 2019-09-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190902_2140'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_note'),
        ),
    ]
